#ifndef HERMAS_IMAGE_FORMAT_H
#define HERMAS_IMAGE_FORMAT_H

/*
 * Canonical graph-image v1 byte layout. These constants describe encoded
 * bytes; an image is always decoded field-by-field, never cast to a native
 * structure.
 */
#define HERMAS_GRAPH_IMAGE_VERSION 1u
#define HERMAS_IMAGE_HEADER_SIZE 80u
#define HERMAS_IMAGE_MAX_SIZE (1024u * 1024u)

#define HERMAS_IMAGE_HEADER_INPUT_TYPE_OFFSET 22u
#define HERMAS_IMAGE_HEADER_ACTION_CONTRACT_COUNT_OFFSET 28u
#define HERMAS_IMAGE_HEADER_NODE_COUNT_OFFSET 30u
#define HERMAS_IMAGE_HEADER_EDGE_COUNT_OFFSET 32u
#define HERMAS_IMAGE_HEADER_ACTION_CONTRACTS_OFFSET 40u
#define HERMAS_IMAGE_HEADER_NODES_OFFSET 48u
#define HERMAS_IMAGE_HEADER_EDGES_OFFSET 52u
#define HERMAS_IMAGE_HEADER_REGION_COUNT_OFFSET 68u
#define HERMAS_IMAGE_HEADER_REGIONS_OFFSET 72u

#define HERMAS_IMAGE_ACTION_CONTRACT_RECORD_SIZE 36u
#define HERMAS_IMAGE_TYPE_RECORD_SIZE 8u
#define HERMAS_IMAGE_NODE_RECORD_SIZE 8u
#define HERMAS_IMAGE_EDGE_RECORD_SIZE 16u
#define HERMAS_IMAGE_REGION_RECORD_SIZE 16u

#endif
