#ifndef HERMAS2_IMAGE_FORMAT_H
#define HERMAS2_IMAGE_FORMAT_H

/*
 * Canonical graph-image v2 byte layout. These constants describe encoded
 * bytes; an image is always decoded field-by-field, never cast to a native
 * structure.
 */
#define HERMAS2_GRAPH_IMAGE_VERSION 2u
#define HERMAS2_IMAGE_HEADER_SIZE 80u

#define HERMAS2_IMAGE_HEADER_INPUT_TYPE_OFFSET 22u
#define HERMAS2_IMAGE_HEADER_NODE_COUNT_OFFSET 30u
#define HERMAS2_IMAGE_HEADER_EDGE_COUNT_OFFSET 32u
#define HERMAS2_IMAGE_HEADER_NODES_OFFSET 48u
#define HERMAS2_IMAGE_HEADER_EDGES_OFFSET 52u
#define HERMAS2_IMAGE_HEADER_REGION_COUNT_OFFSET 68u
#define HERMAS2_IMAGE_HEADER_REGIONS_OFFSET 72u

#define HERMAS2_IMAGE_ACTION_CONTRACT_RECORD_SIZE 36u
#define HERMAS2_IMAGE_TYPE_RECORD_SIZE 8u
#define HERMAS2_IMAGE_NODE_RECORD_SIZE 8u
#define HERMAS2_IMAGE_EDGE_RECORD_SIZE 16u
#define HERMAS2_IMAGE_REGION_RECORD_SIZE 16u

#endif
